/**
 * Expanded Source Registry: ~75 sources covering 35+ jurisdictions.
 * US Federal/States, EU + DPAs, UK, Australia, Canada, APAC, LATAM, Middle East, Africa.
 * Includes government pages, RSS feeds, legal analyses, and think tanks.
 */

export type SourceType = "government_page" | "rss_feed" | "news_search" | "legal_database" | "twitter_search";

export type ReliabilityTier = 1 | 2 | 3 | 4 | 5;

export type RegistrySource = {
  name: string;
  url: string;
  type: SourceType;
  authorityType: "national" | "state" | "local" | "supranational";
  jurisdiction: string;
  jurisdictionCountry: string;
  jurisdictionState?: string;
  reliabilityTier: ReliabilityTier;
  searchKeywords?: string[];
  description: string;
  twitterQuery?: string;
};

const TWITTER_RECENT_SEARCH_URL = "https://api.twitter.com/2/tweets/search/recent";

export const twitterSearchSources: RegistrySource[] = [
  {
    name: "X Search — Under 16 / COPPA",
    url: TWITTER_RECENT_SEARCH_URL,
    type: "twitter_search",
    authorityType: "supranational",
    jurisdiction: "Global",
    jurisdictionCountry: "Global",
    reliabilityTier: 3,
    searchKeywords: ["under 16", "COPPA", "age verification"],
    description: "X recent search for under-16 and COPPA regulatory updates",
    twitterQuery:
      '"under 16" OR "under 16s" OR COPPA OR "age verification" (regulation OR law OR bill OR legislation) -is:retweet',
  },
  {
    name: "X Search — Meta Child Safety",
    url: TWITTER_RECENT_SEARCH_URL,
    type: "twitter_search",
    authorityType: "supranational",
    jurisdiction: "Global",
    jurisdictionCountry: "Global",
    reliabilityTier: 3,
    searchKeywords: ["Meta", "Instagram", "child safety"],
    description: "X recent search for Meta/Facebook/Instagram/WhatsApp child safety and privacy updates",
    twitterQuery:
      '(Meta OR Facebook OR Instagram OR WhatsApp) ("child safety" OR "children\'s privacy" OR "minor" OR "age restriction") -is:retweet',
  },
  {
    name: "X Search — DSA / OSA / KOSA",
    url: TWITTER_RECENT_SEARCH_URL,
    type: "twitter_search",
    authorityType: "supranational",
    jurisdiction: "Global",
    jurisdictionCountry: "Global",
    reliabilityTier: 3,
    searchKeywords: ["DSA", "Online Safety Act", "KOSA"],
    description: "X recent search for DSA/OSA/KOSA updates related to minors",
    twitterQuery:
      '("Digital Services Act" OR DSA OR "Online Safety Act" OR "KOSA") (children OR minors OR teens) -is:retweet',
  },
  {
    name: "X Search — TikTok/Snap/YouTube Compliance",
    url: TWITTER_RECENT_SEARCH_URL,
    type: "twitter_search",
    authorityType: "supranational",
    jurisdiction: "Global",
    jurisdictionCountry: "Global",
    reliabilityTier: 3,
    searchKeywords: ["TikTok", "Snapchat", "YouTube", "compliance"],
    description: "X recent search for platform age verification and child-protection compliance",
    twitterQuery:
      '(TikTok OR Snapchat OR YouTube) ("age verification" OR "parental consent" OR "child protection") compliance -is:retweet',
  },
];

export const sourceRegistry: RegistrySource[] = [
  // ══════════════════════════════════════════════════════════
  // US FEDERAL
  // ══════════════════════════════════════════════════════════
  {
    name: "FTC Children's Privacy (COPPA)",
    url: "https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 5,
    searchKeywords: ["COPPA", "children privacy", "FTC"],
    description: "FTC COPPA rule page — primary US federal child privacy regulation",
  },
  {
    name: "FTC Kids' Privacy (COPPA) News",
    url: "https://www.ftc.gov/news-events/topics/protecting-consumer-privacy-security/kids-privacy-coppa",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 5,
    searchKeywords: ["COPPA", "FTC enforcement", "children privacy"],
    description: "FTC rolling feed of COPPA press releases, enforcement actions, and statements",
  },
  {
    name: "FTC Children's Privacy Business Guidance",
    url: "https://www.ftc.gov/business-guidance/privacy-security/childrens-privacy",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 5,
    searchKeywords: ["COPPA", "compliance", "business guidance"],
    description: "FTC compliance resources for children's privacy",
  },
  {
    name: "Federal Register — COPPA Rule Final Amendments 2025",
    url: "https://www.federalregister.gov/documents/2025/04/22/2025-05904/childrens-online-privacy-protection-rule",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 5,
    searchKeywords: ["COPPA", "final rule", "federal register"],
    description: "Final COPPA rule amendments. Compliance deadline April 22, 2026.",
  },
  {
    name: "FTC COPPA Finalization Press Release (Jan 2025)",
    url: "https://www.ftc.gov/news-events/news/press-releases/2025/01/ftc-finalizes-changes-childrens-privacy-rule-limiting-companies-ability-monetize-kids-data",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 5,
    searchKeywords: ["COPPA", "finalization", "monetization"],
    description: "Key announcement of final rule changes limiting monetization of children's data",
  },
  {
    name: "GovTrack — KOSA S.1748 Tracker",
    url: "https://www.govtrack.us/congress/bills/119/s1748",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 4,
    searchKeywords: ["KOSA", "Kids Online Safety Act", "S.1748"],
    description: "Independent tracking of KOSA bill status and legislative history",
  },
  {
    name: "TechPolicy.Press — KOSA Tracker",
    url: "https://www.techpolicy.press/tracker/kids-online-safety-act-kosa-s-1409/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 3,
    searchKeywords: ["KOSA", "Kids Online Safety Act", "tracker"],
    description: "Detailed KOSA timeline with amendments and political context",
  },

  // ══════════════════════════════════════════════════════════
  // US STATES
  // ══════════════════════════════════════════════════════════
  {
    name: "California AADC (AB-2273)",
    url: "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202120220AB2273",
    type: "government_page",
    authorityType: "state",
    jurisdiction: "California",
    jurisdictionCountry: "United States",
    jurisdictionState: "California",
    reliabilityTier: 5,
    searchKeywords: ["AADC", "age appropriate design", "AB 2273"],
    description: "California Age-Appropriate Design Code Act — landmark state child safety law",
  },
  {
    name: "NY AG — SAFE for Kids Act",
    url: "https://ag.ny.gov/resources/individuals/consumer-issues/technology/protecting-children-online",
    type: "government_page",
    authorityType: "state",
    jurisdiction: "New York",
    jurisdictionCountry: "United States",
    jurisdictionState: "New York",
    reliabilityTier: 5,
    searchKeywords: ["SAFE for Kids", "New York", "addictive feeds"],
    description: "NY AG rulemaking and enforcement page for SAFE for Kids Act",
  },
  {
    name: "Texas AG — SCOPE Act (HB 18)",
    url: "https://www.texasattorneygeneral.gov/consumer-protection/file-consumer-complaint/consumer-privacy-rights/securing-children-online-through-parental-empowerment",
    type: "government_page",
    authorityType: "state",
    jurisdiction: "Texas",
    jurisdictionCountry: "United States",
    jurisdictionState: "Texas",
    reliabilityTier: 5,
    searchKeywords: ["SCOPE Act", "HB 18", "parental consent"],
    description: "Texas SCOPE Act — requires parental consent for minors under 18",
  },
  {
    name: "Florida — HB 3 Online Protections for Minors",
    url: "https://www.flsenate.gov/Committees/billsummaries/2024/html/3354",
    type: "government_page",
    authorityType: "state",
    jurisdiction: "Florida",
    jurisdictionCountry: "United States",
    jurisdictionState: "Florida",
    reliabilityTier: 5,
    searchKeywords: ["Florida HB 3", "social media ban", "under 14"],
    description: "Florida bans social media for under 14; parental consent for 14-15",
  },
  {
    name: "Orrick — US State Online Safety Law Tracker",
    url: "https://onlinesafety.orrick.com/",
    type: "legal_database",
    authorityType: "state",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 4,
    searchKeywords: ["state tracker", "children online safety", "all states"],
    description: "Comprehensive interactive tracker of all US state children's online safety legislation",
  },
  {
    name: "Inside Privacy — State & Federal Minors' Privacy 2025",
    url: "https://www.insideprivacy.com/childrens-privacy/state-and-federal-developments-in-minors-privacy-in-2025/",
    type: "legal_database",
    authorityType: "state",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 4,
    searchKeywords: ["state privacy", "minors", "2025"],
    description: "Covers all 15+ states with enacted children's social media laws in 2025",
  },
  {
    name: "Mayer Brown — States & FTC Children's Privacy Actions",
    url: "https://www.mayerbrown.com/en/insights/publications/2025/02/protecting-the-next-generation-how-states-and-the-ftc-are-holding-businesses-accountable-for-childrens-online-privacy",
    type: "legal_database",
    authorityType: "state",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 4,
    searchKeywords: ["Maryland Kids Code", "Illinois", "Vermont", "FTC enforcement"],
    description: "Covers Maryland Kids Code, IL, SC, VT bills, and FTC enforcement actions",
  },
  {
    name: "Hunton — Arkansas Social Media Safety Act Amendment",
    url: "https://www.hunton.com/privacy-and-information-security-law/arkansas-amends-social-media-safety-act-following-permanent-injunction-by-federal-court",
    type: "legal_database",
    authorityType: "state",
    jurisdiction: "Arkansas",
    jurisdictionCountry: "United States",
    jurisdictionState: "Arkansas",
    reliabilityTier: 4,
    searchKeywords: ["Arkansas", "SB 611", "social media safety"],
    description: "Arkansas amends Social Media Safety Act after injunction, narrows to under-16",
  },

  // ══════════════════════════════════════════════════════════
  // EUROPEAN UNION
  // ══════════════════════════════════════════════════════════
  {
    name: "EU Digital Services Act",
    url: "https://digital-strategy.ec.europa.eu/en/policies/digital-services-act-package",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 5,
    searchKeywords: ["DSA", "Digital Services Act", "minor protection"],
    description: "EU DSA — platform obligations including minor protection provisions",
  },
  {
    name: "EC — DSA Article 28 Minors Guidelines",
    url: "https://digital-strategy.ec.europa.eu/en/library/commission-publishes-guidelines-protection-minors",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 5,
    searchKeywords: ["DSA Article 28", "minors guidelines"],
    description: "EC non-binding guidelines for Article 28(1) DSA compliance. Published July 2025.",
  },
  {
    name: "DSA Article 28 — Full Text",
    url: "https://www.eu-digital-services-act.com/Digital_Services_Act_Article_28.html",
    type: "legal_database",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 5,
    searchKeywords: ["DSA", "Article 28", "online protection minors"],
    description: "Full text of DSA Article 28 on online protection of minors",
  },
  {
    name: "EDPB — Children Topic Documents",
    url: "https://www.edpb.europa.eu/our-work-tools/our-documents/topic/children_en",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 5,
    searchKeywords: ["EDPB", "children", "guidelines"],
    description: "EDPB guidelines, statements, and opinions on children's data",
  },
  {
    name: "EDPB — Data Protection Day 2026 Children Statement",
    url: "https://www.edpb.europa.eu/news/news/2026/data-protection-day-2026-keeping-childrens-personal-data-safe-online_en",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 5,
    searchKeywords: ["EDPB", "children data", "2026"],
    description: "2026 statement on upcoming EDPB guidelines on children's data processing",
  },
  {
    name: "EU FRA — Consent Ages Across Member States",
    url: "https://fra.europa.eu/en/publication/2017/mapping-minimum-age-requirements-concerning-rights-child-eu/consent-use-data-children",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 5,
    searchKeywords: ["consent age", "GDPR", "member states"],
    description: "Maps consent ages across all EU member states (ranges 13-16)",
  },

  // ══════════════════════════════════════════════════════════
  // EU MEMBER STATE DPAs
  // ══════════════════════════════════════════════════════════
  {
    name: "France CNIL — Digital Rights of Children",
    url: "https://www.cnil.fr/en/topics/digital-rights-children",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "France",
    jurisdictionCountry: "France",
    reliabilityTier: 5,
    searchKeywords: ["CNIL", "children digital rights"],
    description: "CNIL 8 recommendations for protecting children online",
  },
  {
    name: "France CNIL — 8 Recommendations for Children Online",
    url: "https://www.cnil.fr/en/cnil-publishes-8-recommendations-enhance-protection-children-online",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "France",
    jurisdictionCountry: "France",
    reliabilityTier: 5,
    searchKeywords: ["CNIL", "profiling", "age verification", "parental controls"],
    description: "CNIL recommendations on profiling, age verification, and parental controls",
  },
  {
    name: "Ireland DPC — Child-Oriented Data Processing Fundamentals",
    url: "https://www.dataprotection.ie/en/dpc-guidance/fundamentals-child-oriented-approach-data-processing",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Ireland",
    jurisdictionCountry: "Ireland",
    reliabilityTier: 5,
    searchKeywords: ["DPC Ireland", "child-oriented", "data processing"],
    description: "14 core principles for child-centred data processing from Ireland DPC",
  },
  {
    name: "Germany BfDI",
    url: "https://www.bfdi.bund.de/EN/Home/home_node.html",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Germany",
    jurisdictionCountry: "Germany",
    reliabilityTier: 5,
    searchKeywords: ["BfDI", "children data Germany"],
    description: "German Federal Data Protection Commissioner",
  },
  {
    name: "Italy Garante Privacy",
    url: "https://www.garanteprivacy.it/web/garante-privacy-en",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Italy",
    jurisdictionCountry: "Italy",
    reliabilityTier: 5,
    searchKeywords: ["Garante", "TikTok ban", "children Italy"],
    description: "Italian DPA — active on children's social media enforcement",
  },
  {
    name: "Spain AEPD — Children's Digital Protection",
    url: "https://www.aepd.es/en/press-and-communication/press-releases/aepd-publishes-analysis-on-protection-of-children-and-adolescents-in-the-digital-environment",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Spain",
    jurisdictionCountry: "Spain",
    reliabilityTier: 5,
    searchKeywords: ["AEPD", "children digital", "Spain"],
    description: "AEPD analysis on data protection principles for minors (Oct 2024)",
  },
  {
    name: "Netherlands — Autoriteit Persoonsgegevens",
    url: "https://www.autoriteitpersoonsgegevens.nl/en",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Netherlands",
    jurisdictionCountry: "Netherlands",
    reliabilityTier: 5,
    searchKeywords: ["AP", "Netherlands", "consent age 16"],
    description: "Dutch DPA — consent age is 16 under UAVG",
  },

  // ══════════════════════════════════════════════════════════
  // UNITED KINGDOM
  // ══════════════════════════════════════════════════════════
  {
    name: "GOV.UK — Online Safety Act Explainer",
    url: "https://www.gov.uk/government/publications/online-safety-act-explainer/online-safety-act-explainer",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    jurisdictionCountry: "United Kingdom",
    reliabilityTier: 5,
    searchKeywords: ["Online Safety Act", "explainer", "UK"],
    description: "Official government explainer. Child safety regime fully in effect by Summer 2025.",
  },
  {
    name: "Ofcom — Children's Safety Codes Statement",
    url: "https://www.ofcom.org.uk/online-safety/illegal-and-harmful-content/statement-protecting-children-from-harms-online",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    jurisdictionCountry: "United Kingdom",
    reliabilityTier: 5,
    searchKeywords: ["Ofcom", "children safety codes", "July 2025"],
    description: "Children's Safety Codes of Practice — in force July 25, 2025",
  },
  {
    name: "Ofcom — Quick Guide to Children's Safety Codes",
    url: "https://www.ofcom.org.uk/online-safety/illegal-and-harmful-content/quick-guide-to-childrens-safety-codes",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    jurisdictionCountry: "United Kingdom",
    reliabilityTier: 5,
    searchKeywords: ["Ofcom", "children protection", "quick guide"],
    description: "Summary of all regulatory documents for children's protection duties",
  },
  {
    name: "ICO — Children's Code Guidance",
    url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/childrens-information/childrens-code-guidance-and-resources/",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    jurisdictionCountry: "United Kingdom",
    reliabilityTier: 5,
    searchKeywords: ["ICO", "children's code", "AADC UK"],
    description: "UK ICO Children's Code — 15 standards for online services accessed by children",
  },
  {
    name: "UK Online Safety Act 2023",
    url: "https://www.legislation.gov.uk/ukpga/2023/50/contents/enacted",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    jurisdictionCountry: "United Kingdom",
    reliabilityTier: 5,
    searchKeywords: ["Online Safety Act", "UK child safety"],
    description: "UK Online Safety Act 2023 — comprehensive child safety duties",
  },

  // ══════════════════════════════════════════════════════════
  // AUSTRALIA
  // ══════════════════════════════════════════════════════════
  {
    name: "eSafety — Social Media Age Restrictions",
    url: "https://www.esafety.gov.au/about-us/industry-regulation/social-media-age-restrictions",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Australia",
    jurisdictionCountry: "Australia",
    reliabilityTier: 5,
    searchKeywords: ["eSafety", "social media ban", "under 16"],
    description: "Under-16 social media ban — in effect December 10, 2025",
  },
  {
    name: "eSafety — Young People Social Media Restrictions",
    url: "https://www.esafety.gov.au/young-people/social-media-age-restrictions",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Australia",
    jurisdictionCountry: "Australia",
    reliabilityTier: 5,
    searchKeywords: ["Facebook", "Instagram", "Threads", "restricted platforms"],
    description: "Lists all 10 restricted platforms: Facebook, Instagram, Threads, TikTok, etc.",
  },
  {
    name: "Australia — Social Media Minimum Age Policy",
    url: "https://www.infrastructure.gov.au/media-communications/internet/online-safety/social-media-minimum-age",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Australia",
    jurisdictionCountry: "Australia",
    reliabilityTier: 5,
    searchKeywords: ["minimum age", "Online Safety Amendment Act 2024"],
    description: "Dept of Infrastructure policy page on Online Safety Amendment Act 2024",
  },
  {
    name: "Australia Online Safety Act 2021",
    url: "https://www.legislation.gov.au/C2021A00076/latest/text",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Australia",
    jurisdictionCountry: "Australia",
    reliabilityTier: 5,
    searchKeywords: ["Online Safety Act", "Australia"],
    description: "Australia Online Safety Act 2021 and subsequent amendments",
  },

  // ══════════════════════════════════════════════════════════
  // CANADA
  // ══════════════════════════════════════════════════════════
  {
    name: "Canada Online Harms Act (C-63) LEGISinfo",
    url: "https://www.parl.ca/legisinfo/en/bill/44-1/c-63",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Canada",
    jurisdictionCountry: "Canada",
    reliabilityTier: 5,
    searchKeywords: ["C-63", "Online Harms Act", "Canada"],
    description: "Canada Online Harms Act (Bill C-63) — died on Order Paper Jan 2025",
  },
  {
    name: "DOJ Canada — Bill C-63 Charter Statement",
    url: "https://www.justice.gc.ca/eng/csj-sjc/pl/charter-charte/c63.html",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Canada",
    jurisdictionCountry: "Canada",
    reliabilityTier: 5,
    searchKeywords: ["C-63", "Charter", "online harms"],
    description: "Charter analysis of Online Harms Act provisions",
  },
  {
    name: "OPC Canada — Bill S-210 Analysis",
    url: "https://www.priv.gc.ca/en/privacy-and-transparency-at-the-opc/proactive-disclosure/opc-parl-bp/secu_20240527/is_20240527/?id=7777-6-642162",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Canada",
    jurisdictionCountry: "Canada",
    reliabilityTier: 5,
    searchKeywords: ["S-210", "children data", "privacy commissioner"],
    description: "Comparison of S-210, C-63, and C-27 re: children's data",
  },

  // ══════════════════════════════════════════════════════════
  // ASIA-PACIFIC
  // ══════════════════════════════════════════════════════════
  {
    name: "China — Regulations on Protection of Minors Online",
    url: "https://www.chinalawtranslate.com/en/online-protection-of-minors/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "China",
    jurisdictionCountry: "China",
    reliabilityTier: 4,
    searchKeywords: ["China", "minors online", "CAC"],
    description: "Full English translation. In effect January 1, 2024.",
  },
  {
    name: "China — Overview of Minors Online Protections",
    url: "https://www.chinalawtranslate.com/en/overview-of-protections-for-minors-online/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "China",
    jurisdictionCountry: "China",
    reliabilityTier: 4,
    searchKeywords: ["China", "minors", "comparison table"],
    description: "Comparison table of all Chinese children's online protection regulations",
  },
  {
    name: "Singapore PDPC — Children's Data Guidelines",
    url: "https://www.pdpc.gov.sg/guidelines-and-consultation/2024/03/advisory-guidelines-on-the-pdpa-for-childrens-personal-data-in-the-digital-environment",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "Singapore",
    jurisdictionCountry: "Singapore",
    reliabilityTier: 5,
    searchKeywords: ["PDPC", "children data", "PDPA"],
    description: "Advisory Guidelines on PDPA for children's personal data. Issued March 2024.",
  },
  {
    name: "South Korea Youth Protection Act",
    url: "https://elaw.klri.re.kr/eng_service/lawView.do?hseq=38401&lang=ENG",
    type: "government_page",
    authorityType: "national",
    jurisdiction: "South Korea",
    jurisdictionCountry: "South Korea",
    reliabilityTier: 5,
    searchKeywords: ["youth protection", "South Korea", "gaming curfew"],
    description: "Full English translation of South Korea Youth Protection Act",
  },
  {
    name: "India — DPDP Act Children's Data (K&S Analysis)",
    url: "https://ksandk.com/data-protection-and-data-privacy/childrens-data-protection-under-indias-dpdp-rules/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "India",
    jurisdictionCountry: "India",
    reliabilityTier: 3,
    searchKeywords: ["DPDP", "children data", "India", "parental consent"],
    description: "Analysis of Rules 10-12: parental consent, no tracking/ads for under-18s",
  },
  {
    name: "India — ORF DPDP Rules Child Data Safety",
    url: "https://www.orfonline.org/expert-speak/dpdp-rules-and-the-future-of-child-data-safety",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "India",
    jurisdictionCountry: "India",
    reliabilityTier: 3,
    searchKeywords: ["India", "DPDP rules", "child data safety"],
    description: "Expert analysis of India's child data protection implementation challenges",
  },
  {
    name: "A&O Shearman — APAC Children's Data Privacy Trends",
    url: "https://www.aoshearman.com/en/insights/ao-shearman-on-data/navigating-consent-emerging-trends-in-childrens-data-privacy-across-apac",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "APAC",
    jurisdictionCountry: "APAC",
    reliabilityTier: 4,
    searchKeywords: ["APAC", "children data", "Singapore", "Japan", "Philippines", "Thailand"],
    description: "Children's data privacy trends across APAC (September 2025)",
  },
  {
    name: "ITIF — China Minor Mode Analysis",
    url: "https://itif.org/publications/2025/05/09/chinas-minors-mode-blueprint-or-cautionary-tale/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "China",
    jurisdictionCountry: "China",
    reliabilityTier: 3,
    searchKeywords: ["China", "minor mode", "CAC"],
    description: "Analysis of China's CAC minor mode requirements (April 2025)",
  },
  {
    name: "Hunton — China Draft Measures for Minors Online",
    url: "https://www.hunton.com/privacy-and-information-security-law/china-issued-draft-rules-for-identifying-online-service-providers-subject-to-the-regulations-on-the-protection-of-minors-online",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "China",
    jurisdictionCountry: "China",
    reliabilityTier: 4,
    searchKeywords: ["China", "CAC", "draft measures", "minors"],
    description: "CAC Draft Measures Sep 2025 for identifying platforms with substantial minor users",
  },

  // ══════════════════════════════════════════════════════════
  // LATIN AMERICA
  // ══════════════════════════════════════════════════════════
  {
    name: "Brazil — ECA Digital Law (Inside Privacy)",
    url: "https://www.insideprivacy.com/childrens-privacy/brazil-adopts-law-protecting-minors-online/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "Brazil",
    jurisdictionCountry: "Brazil",
    reliabilityTier: 4,
    searchKeywords: ["Brazil", "ECA Digital", "minors online"],
    description: "ECA Digital law signed September 2025 — comprehensive children's online protection",
  },
  {
    name: "Brazil — IAPP Child Online Safety Bill Analysis",
    url: "https://iapp.org/news/a/inside-brazil-s-child-online-safety-bill",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "Brazil",
    jurisdictionCountry: "Brazil",
    reliabilityTier: 4,
    searchKeywords: ["Brazil", "Bill 2628/2022", "children digital"],
    description: "Analysis of Bill 2628/2022 establishing safeguards for children in digital environments",
  },
  {
    name: "Brazil — HRW Landmark Law Report",
    url: "https://www.hrw.org/news/2025/09/17/brazil-passes-landmark-law-to-protect-children-online",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "Brazil",
    jurisdictionCountry: "Brazil",
    reliabilityTier: 3,
    searchKeywords: ["Brazil", "landmark law", "children online"],
    description: "Human Rights Watch report on Brazil's children's online safety law",
  },

  // ══════════════════════════════════════════════════════════
  // MIDDLE EAST & AFRICA
  // ══════════════════════════════════════════════════════════
  {
    name: "DLA Piper — South Africa POPIA",
    url: "https://www.dlapiperdataprotection.com/index.html?t=law&c=ZA",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "South Africa",
    jurisdictionCountry: "South Africa",
    reliabilityTier: 4,
    searchKeywords: ["POPIA", "South Africa", "children data"],
    description: "POPIA data protection law with children's data provisions",
  },
  {
    name: "Secure Privacy — UAE Data Protection Guide",
    url: "https://secureprivacy.ai/blog/uae-data-protection-law-guide",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "UAE",
    jurisdictionCountry: "UAE",
    reliabilityTier: 3,
    searchKeywords: ["UAE", "PDPL", "children data"],
    description: "UAE data protection law guide including children's provisions",
  },
  {
    name: "Secure Privacy — Nigeria Data Protection Guide",
    url: "https://secureprivacy.ai/blog/nigeria-data-protection-law",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "Nigeria",
    jurisdictionCountry: "Nigeria",
    reliabilityTier: 3,
    searchKeywords: ["Nigeria", "NDPA", "data protection"],
    description: "Nigeria Data Protection Act 2023 compliance guide",
  },
  {
    name: "Africa HR — Data Laws Across Africa",
    url: "https://africa-hr.com/blog/data-laws-across-africa/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "Africa",
    jurisdictionCountry: "Africa",
    reliabilityTier: 3,
    searchKeywords: ["POPIA", "NDPA", "Kenya", "Ghana", "Morocco"],
    description: "Data protection laws across Africa: SA, Nigeria, Kenya, Ghana, Morocco",
  },

  // ══════════════════════════════════════════════════════════
  // INTERNATIONAL ORGANIZATIONS
  // ══════════════════════════════════════════════════════════
  {
    name: "UN — Child and Youth Safety Online",
    url: "https://www.un.org/en/global-issues/child-and-youth-safety-online",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 5,
    searchKeywords: ["UN", "child safety", "ITU", "UNICEF"],
    description: "UN portal for child safety online — links to ITU, UNICEF, global initiatives",
  },
  {
    name: "ITU — Child Online Protection Guidelines",
    url: "https://www.itu-cop-guidelines.com/",
    type: "government_page",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 5,
    searchKeywords: ["ITU", "COP", "child online protection"],
    description: "ITU comprehensive guidelines for all stakeholders on child online protection",
  },

  // ══════════════════════════════════════════════════════════
  // THINK TANKS & ADVOCACY
  // ══════════════════════════════════════════════════════════
  {
    name: "5Rights Foundation",
    url: "https://5rightsfoundation.com/",
    type: "legal_database",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 4,
    searchKeywords: ["5Rights", "children digital rights"],
    description: "Leading NGO for children's digital rights — advocated for DSA, AADC, UK OSA",
  },
  {
    name: "Common Sense Media",
    url: "https://www.commonsense.org/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 3,
    searchKeywords: ["Common Sense", "children privacy", "legislation"],
    description: "Major advocate for children's privacy legislation",
  },
  {
    name: "IWF — Online Safety Act Explained",
    url: "https://www.iwf.org.uk/policy-work/the-online-safety-act-osa-explained/",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    jurisdictionCountry: "United Kingdom",
    reliabilityTier: 4,
    searchKeywords: ["IWF", "CSAM", "Online Safety Act"],
    description: "Internet Watch Foundation explainer on UK OSA implementation",
  },
  {
    name: "WeProtect Global Alliance — Global Threat Assessment",
    url: "https://www.weprotect.org/global-threat-assessment-23/",
    type: "legal_database",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 4,
    searchKeywords: ["WeProtect", "child exploitation", "threat assessment"],
    description: "Annual threat assessment on child sexual exploitation online",
  },
  {
    name: "GPEN Enforcement Sweep — Children's Data Protection",
    url: "https://www.insideprivacy.com/childrens-privacy/global-privacy-regulators-launch-enforcement-sweep-focused-on-childrens-data-protection/",
    type: "legal_database",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 4,
    searchKeywords: ["GPEN", "enforcement sweep", "FTC", "ICO", "CNIL"],
    description: "Nov 2025 coordinated enforcement sweep by FTC, CA AG, CPPA, ICO, CNIL, DPC",
  },
  {
    name: "Hunton — FTC COPPA Rule Final Amendments",
    url: "https://www.hunton.com/privacy-and-information-security-law/ftc-publishes-final-coppa-rule-amendments",
    type: "legal_database",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 4,
    searchKeywords: ["COPPA", "final amendments", "compliance"],
    description: "Detailed analysis of COPPA amendments. Compliance deadline April 22, 2026.",
  },
  {
    name: "Reuters — Global Children's Social Media Legislation",
    url: "https://www.reuters.com/world/asia-pacific/australia-europe-countries-move-curb-childrens-social-media-access-2026-02-17/",
    type: "news_search",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 3,
    searchKeywords: ["global", "children", "social media", "legislation"],
    description: "Feb 2026 Reuters overview of global children's social media legislative developments",
  },
  {
    name: "TechPolicy.Press — US States Child Safety 2026 Outlook",
    url: "https://www.techpolicy.press/what-to-expect-from-us-states-on-child-online-safety-in-2026/",
    type: "news_search",
    authorityType: "state",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 3,
    searchKeywords: ["US states", "2026", "child online safety"],
    description: "Expert roundtable on 2026 state legislative outlook (Jan 2026)",
  },

  // ══════════════════════════════════════════════════════════
  // RSS FEEDS — Google News (5 items per feed)
  // ══════════════════════════════════════════════════════════
  {
    name: "Google News — KOSA Kids Online Safety Act",
    url: "https://news.google.com/rss/search?q=KOSA+Kids+Online+Safety+Act+2024+2025",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 3,
    description: "News coverage of Kids Online Safety Act",
  },
  {
    name: "Google News — COPPA 2.0 Children Privacy",
    url: "https://news.google.com/rss/search?q=COPPA+2.0+children+privacy+teen+2024+2025",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 3,
    description: "News about COPPA 2.0 extending protections to teens",
  },
  {
    name: "Google News — Children Online Safety Regulation",
    url: "https://news.google.com/rss/search?q=%22children+online+safety%22+regulation&hl=en-US&gl=US&ceid=US:en",
    type: "rss_feed",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 2,
    description: "Global children's online safety regulation news",
  },
  {
    name: "Google News — Social Media Kids Law",
    url: "https://news.google.com/rss/search?q=%22social+media%22+%22kids%22+law&hl=en-US&gl=US&ceid=US:en",
    type: "rss_feed",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 2,
    description: "Social media children's legislation news",
  },
  {
    name: "Google News — COPPA Regulation",
    url: "https://news.google.com/rss/search?q=COPPA+regulation&hl=en-US&gl=US&ceid=US:en",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "United States",
    jurisdictionCountry: "United States",
    reliabilityTier: 2,
    description: "COPPA-specific news feed",
  },
  {
    name: "Google News — Teen Online Safety",
    url: "https://news.google.com/rss/search?q=%22teen+online+safety%22&hl=en-US&gl=US&ceid=US:en",
    type: "rss_feed",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 2,
    description: "Teen online safety news",
  },
  {
    name: "Google News — Children Data Protection GDPR",
    url: "https://news.google.com/rss/search?q=%22children%22+%22data+protection%22+GDPR&hl=en-US&gl=US&ceid=US:en",
    type: "rss_feed",
    authorityType: "supranational",
    jurisdiction: "European Union",
    jurisdictionCountry: "European Union",
    reliabilityTier: 2,
    description: "EU-focused children's data protection news",
  },
  {
    name: "Google News — Meta Children Safety",
    url: "https://news.google.com/rss/search?q=Meta+children+safety&hl=en-US&gl=US&ceid=US:en",
    type: "rss_feed",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 2,
    description: "Meta-specific children's safety news",
  },
  {
    name: "Google News — China Children Internet Regulation",
    url: "https://news.google.com/rss/search?q=China+children+internet+regulation+minor+protection+2024+2025",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "China",
    jurisdictionCountry: "China",
    reliabilityTier: 3,
    description: "China regulations on minors' internet use",
  },
  {
    name: "Google News — South Korea Youth Online",
    url: "https://news.google.com/rss/search?q=South+Korea+youth+online+protection+children+internet+2024+2025",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "South Korea",
    jurisdictionCountry: "South Korea",
    reliabilityTier: 3,
    description: "South Korea youth online protection coverage",
  },
  {
    name: "Google News — Japan Children Online Safety",
    url: "https://news.google.com/rss/search?q=Japan+children+online+safety+regulation+social+media+2024+2025",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "Japan",
    jurisdictionCountry: "Japan",
    reliabilityTier: 3,
    description: "Japan children's online safety regulation",
  },
  {
    name: "Google News — Online Safety Children Age Verification",
    url: "https://news.google.com/rss/search?q=online+safety+children+regulation+age+verification+2024+2025",
    type: "rss_feed",
    authorityType: "supranational",
    jurisdiction: "International",
    jurisdictionCountry: "International",
    reliabilityTier: 3,
    description: "Global online safety and age verification regulation",
  },
  {
    name: "Google News — Brazil Children Online Protection",
    url: "https://news.google.com/rss/search?q=Brazil+children+online+protection+digital+safety+2024+2025",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "Brazil",
    jurisdictionCountry: "Brazil",
    reliabilityTier: 3,
    description: "Brazil children's online protection regulation coverage",
  },
  {
    name: "Google News — UAE Children Digital Safety",
    url: "https://news.google.com/rss/search?q=UAE+children+digital+safety+regulation+2025+2026",
    type: "rss_feed",
    authorityType: "national",
    jurisdiction: "UAE",
    jurisdictionCountry: "UAE",
    reliabilityTier: 3,
    description: "UAE Federal Decree Law on Child Digital Safety coverage",
  },
];

/** Get all sources for a specific jurisdiction */
export function getSourcesByJurisdiction(country: string): RegistrySource[] {
  return sourceRegistry.filter(
    (s) => s.jurisdictionCountry === country || s.jurisdiction === country,
  );
}

/** Get sources at or above a reliability threshold */
export function getSourcesByMinReliability(minTier: ReliabilityTier): RegistrySource[] {
  return sourceRegistry.filter((s) => s.reliabilityTier >= minTier);
}

/** Get all unique jurisdictions in the registry */
export function getRegisteredJurisdictions(): string[] {
  return [...new Set(sourceRegistry.map((s) => s.jurisdictionCountry))];
}
